### ISSUE TITLE
Метрополитен 1

### ISSUE THREAD

**Issue by DanyaKrov** [DanyaKrov/c-_wasp_academy_homeworks#1]
@vdetstvepil

**Comment by vdetstvepil** [comment]
Класс Line.cs, Metro.cs, Station.cs пустые 👀 Либо ты забыл коммитнуть изменения, либо ... ?

**Comment by vdetstvepil** [comment]
Если забыл коммитнуть, коммитни и пушни, тогда изменения отобразятся в репозитории. Если просто не сделал задачу, то сделай и пришли решение) Тегни, как появится апдейт

**Comment by DanyaKrov** [comment]
@vdetstvepil, похоже я забыл запушить в тот раз

**Comment by vdetstvepil** [comment]
О, появилось. В 22 строке файла Station.cs ты присваиваешь своему списку ссылку на список, который прилетел в конструктор в виде параметра. Т.е. если список, который параметр, ты удалишь или изменишь извне, то же самое произойдет и с полем твоего класса. Поэтому тебе надо делать не ссылку на другой список, а копипастить элементы из этого другого списка в свой. Воспользуйся циклом foreach, чтобы пробежаться по списку и добавить поштучно элементы в список класса, или используй функцию AddRange().

**Comment by vdetstvepil** [comment]
Поправь этот косяк, и зачту.

**Comment by DanyaKrov** [comment]
@vdetstvepil, исправил

**Comment by vdetstvepil** [comment]
Вылетит ошибка, если так будешь обращаться со списком. Он же у тебя пустой! Как ты можешь обратиться по индексу к его элементам? Воспользуйся функцией AddRange, т.е.  `list = new List<Station>; list.AddRange(anothelist);`

Отправлять на проверку еще раз не нужно, но поправь косяк, иначе аукнется в будущем.

**Comment by vdetstvepil** [comment]
Принято.
