### ISSUE TITLE
1 дз по SQL

### ISSUE THREAD

**Issue by DanyaKrov** [DanyaKrov/c-_wasp_academy_homeworks#10]
@vdetstvepil, я конвертировал txt в pdf, но там почему-то пропали русские буквы. Поэтому я закинул в обоих форматах

**Comment by DanyaKrov** [comment]
https://github.com/DanyaKrov/c-_wasp_academy_homeworks/blob/main/SQL/homework1.txt

**Comment by vdetstvepil** [comment]
Зачтено.
