### ISSUE TITLE
1 дз по Unity

### ISSUE THREAD

**Issue by DanyaKrov** [DanyaKrov/c-_wasp_academy_homeworks#9]
@shadowAnonim , проект в этом репозитории: https://github.com/DanyaKrov/1hw_unity

**Comment by shadowAnonim** [comment]
Отсутствует объект дерева, из-за чего невозможно понять, где появится следующее яблоко. -2
Управление стрелочками, вместо курсора мыши, как в ТЗ. -1

Итого: 1/4, если хочешь, можешь переделать.

**Comment by DanyaKrov** [comment]
@shadowAnonim , я исправил,  https://github.com/DanyaKrov/1hw_unity
